/**
 * Safe, server-side environment validation.
 *
 * Two secrets drive the whole application:
 *
 *   DATABASE_URL  — the Neon PostgreSQL connection string (read by the Prisma
 *                   CLI through `prisma.config.ts` and by the runtime client
 *                   through `@prisma/adapter-pg`).
 *   AUTH_SECRET   — a cryptographically random 32-byte base64 value that signs
 *                   the HTTP-only session cookie (JWT / HS256 via `jose`).
 *
 * This module validates both by SHAPE and fails loudly with an actionable,
 * human-readable message — but it NEVER echoes the configured value, so a
 * misconfigured server log or error page cannot leak the database password or
 * the signing secret into a browser or a public log.
 *
 * It must stay importable from edge contexts (`src/proxy.ts`), so it depends
 * on nothing but plain JavaScript.
 */

/** Configuration problem — safe to log, safe to show the name (not the value). */
export class EnvConfigError extends Error {
  readonly code = "ENV_CONFIG";
  constructor(message: string) {
    super(message);
    this.name = "EnvConfigError";
  }
}

const GENERATE_SECRET_CMD =
  'node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'base64\'))"';

const POSTGRES_SCHEME = /^postgres(?:ql)?:\/\//i;

/** 32 random bytes → 44 base64 characters. Anything shorter is not acceptable. */
const AUTH_SECRET_MIN_LENGTH = 32;

let cachedDatabaseUrl: string | undefined;
let cachedAuthSecret: string | undefined;

/** True for empty values or obvious copy-paste placeholders from `.env.example`. */
function isPlaceholder(value: string): boolean {
  const v = value.trim().toLowerCase();
  if (!v) return true;
  return (
    v === "undefined" ||
    v === "null" ||
    v === "replace-me" ||
    v.includes("your_neon") ||
    v.includes("your_random") ||
    v.includes("replace-me") ||
    v.includes("replace_me") ||
    v.includes("changeme") ||
    v.includes("your_connection") ||
    v.includes("your_database")
  );
}

/**
 * Returns the validated PostgreSQL connection string.
 * Throws {@link EnvConfigError} when missing, placeholder, or not a Postgres URL.
 */
export function getDatabaseUrl(): string {
  if (cachedDatabaseUrl) return cachedDatabaseUrl;

  const raw = process.env.DATABASE_URL;
  if (!raw || isPlaceholder(raw)) {
    throw new EnvConfigError(
      "DATABASE_URL is missing or still a placeholder. Copy .env.example to .env and set DATABASE_URL to your " +
        "Neon PostgreSQL pooled connection string (postgresql://…?sslmode=require)."
    );
  }

  const value = raw.trim();
  if (!POSTGRES_SCHEME.test(value)) {
    throw new EnvConfigError(
      "DATABASE_URL is not a PostgreSQL connection string. It must start with postgresql:// (your Neon pooled " +
        "connection string) — a website URL or Neon Auth URL cannot be used as the database."
    );
  }

  cachedDatabaseUrl = value;
  return value;
}

/**
 * Returns the validated JWT signing secret.
 *
 * Rejects exactly the misconfigurations that break login in practice:
 * a Neon Auth URL pasted into AUTH_SECRET, the database connection string,
 * `undefined`/`null`, placeholders, short strings and other predictable values.
 */
export function getAuthSecret(): string {
  if (cachedAuthSecret) return cachedAuthSecret;

  const raw = process.env.AUTH_SECRET;
  if (!raw || isPlaceholder(raw)) {
    throw new EnvConfigError(
      `AUTH_SECRET is missing or still a placeholder. Generate a cryptographically random 32-byte secret with: ` +
        `${GENERATE_SECRET_CMD} and put the value in .env as AUTH_SECRET="…".`
    );
  }

  const value = raw.trim();

  if (/^https?:\/\//i.test(value) || value.includes("://")) {
    throw new EnvConfigError(
      "AUTH_SECRET is a URL or connection string (a Neon Auth URL is NOT a valid signing secret). Replace it " +
        `with a random 32-byte base64 secret generated by: ${GENERATE_SECRET_CMD}`
    );
  }

  if (value.length < AUTH_SECRET_MIN_LENGTH) {
    throw new EnvConfigError(
      `AUTH_SECRET is too short to be a safe signing key (at least ${AUTH_SECRET_MIN_LENGTH} characters are ` +
        `required). Generate one with: ${GENERATE_SECRET_CMD}`
    );
  }

  if (/^(?:secret|password|passwd|pass|key|test|dev|demo|prod|production|admin)[\w!@#$.-]*$/i.test(value)) {
    throw new EnvConfigError(
      `AUTH_SECRET is a predictable string, not a random secret. Generate one with: ${GENERATE_SECRET_CMD}`
    );
  }

  const databaseUrl = process.env.DATABASE_URL?.trim();
  if (databaseUrl && value === databaseUrl) {
    throw new EnvConfigError(
      "AUTH_SECRET must not be the database connection string. Use a separate random secret generated by: " +
        `${GENERATE_SECRET_CMD}`
    );
  }

  cachedAuthSecret = value;
  return value;
}

/**
 * Startup check used by `src/instrumentation.ts`: validates both required
 * secrets and throws one clear, value-free configuration error if anything is
 * wrong. Safe to call more than once.
 */
export function validateServerEnv(): void {
  getDatabaseUrl();
  getAuthSecret();
}
